theme = "rose_pine"

[editor]
line-number = "relative"
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.insert.k]
j = "normal_mode"

[keys.normal.g]
a = "code_action"

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"
